import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { fetchContentReports, updateContentReport } from '@/services/api'
import { useProcessing } from '@/hooks/useProcessing'
import { ShieldAlert } from 'lucide-react'
import toast from 'react-hot-toast'

export default function AdminModeration() {
  const qc = useQueryClient(); const process = useProcessing()
  const { data = [], isLoading } = useQuery({ queryKey: ['admin-content-reports'], queryFn: () => fetchContentReports().then(result => result.data ?? []) })
  const mutation = useMutation({ mutationFn: ({ id, status }: { id: string; status: 'reviewing' | 'resolved' | 'dismissed' }) => process('Đang cập nhật hàng đợi kiểm duyệt…', async () => { const result = await updateContentReport(id, status); if (result.error) throw result.error }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin-content-reports'] }); toast.success('Đã cập nhật báo cáo') }, onError: (error: unknown) => toast.error(error instanceof Error ? error.message : 'Không thể cập nhật') })
  return <div className="p-8"><div className="flex items-center gap-3 mb-6"><ShieldAlert className="text-orange-400" /><div><h1 className="text-2xl font-bold" style={{ fontFamily: 'var(--font-family-display)' }}>Hàng đợi kiểm duyệt</h1><p className="text-sm" style={{ color: 'var(--text-muted)' }}>Báo cáo spam, vi phạm và Reels cần xem xét.</p></div></div><div className="space-y-3">{isLoading ? <div className="skeleton h-24 rounded-xl" /> : data.length === 0 ? <div className="empty-state">Chưa có báo cáo nội dung.</div> : data.map(report => <div key={report.id} className="card p-5 flex flex-wrap items-center gap-4"><div className="flex-1"><div className="flex gap-2 items-center"><span className="badge badge-orange text-xs">{report.status}</span><strong>{report.target_type}</strong></div><p className="text-sm mt-2" style={{ color: 'var(--text-secondary)' }}>{report.reason}</p><p className="text-xs" style={{ color: 'var(--text-muted)' }}>Bởi {report.reporter?.username ?? 'Thành viên'}</p></div><div className="flex gap-2"><button className="btn-secondary text-xs" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: report.id, status: 'reviewing' })}>Đang xem</button><button className="btn-primary text-xs" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: report.id, status: 'resolved' })}>Đã xử lý</button><button className="btn-ghost text-xs" disabled={mutation.isPending} onClick={() => mutation.mutate({ id: report.id, status: 'dismissed' })}>Bỏ qua</button></div></div>)}</div></div>
}
